[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"

optimizer = true
optimizer_runs = 200
# via_ir = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${ETH_RPC_URL}"
localhost = "http://127.0.0.1:8545"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
